services:
    app:
        build: .
        container_name: taskly_backend
        volumes:
            - .:/var/www
        command: >
            sh -c "mkdir -p /var/www/storage /var/www/bootstrap/cache &&
                   chown -R www-data:www-data /var/www/storage /var/www/bootstrap/cache &&
                   php-fpm"
        depends_on:
            - db
        networks:
            - taskly

    nginx:
        image: nginx:latest
        container_name: taskly_nginx
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - taskly

    db:
        image: mysql:8.0
        container_name: taskly_mysql
        environment:
            MYSQL_DATABASE: taskly
            MYSQL_USER: taskly_user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: rootpassword
        volumes:
            - taskly:/var/lib/mysql
        networks:
            - taskly

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: taskly_phpmyadmin
        restart: always
        ports:
            - "6080:80"
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: rootpassword
        depends_on:
            - db
        networks:
            - taskly

volumes:
    taskly:

networks:
    taskly:
        driver: bridge
